name: activity
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python==3.8.10
  - pytorch==1.8.1
  - numpy==1.21.2
  - h5py==3.4.0
  - pywavelets==1.1.1
  - pillow==8.3.2
  - mlflow==1.20.2
  - torchvision==0.2.2
  - cloudpickle==1.6.0
  - yapf==0.31.0
  - pylint==2.11.1
  - pandas==1.3.4
  - matplotlib==3.5.1
  - pip
  - pip:
      - azureml-core==1.34.0
      - azureml-pipeline==1.34.0
      - azureml-mlflow==1.34.0
      - ray[tune]==1.6.0
